application:
  name: simple-node-app
  project: ${RANDOM_STR_PLACEHOLDER}
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: simple-node-app
        paths:
          - /*
