FROM bitnami/mongodb:3.6.20-debian-9-r36
USER root
RUN apt-get update && apt-get -y install mini-httpd netcat-openbsd vim
USER 1001
COPY rds-combined-ca-bundle.pem run.sh insert.json select.json /
WORKDIR /
CMD ["/run.sh"]
